version: 0.2
  
phases:
   build:
     commands:
       - echo Entered the build phase..
       - mvn clean package
   post_build: 
     commands: 
       - echo Build complete success
artifacts:
   files:
      - target/calculator-ms.jar
   discard-paths: yes